import type { ContactListItem, FollowUp, Message } from "./types";

const now = Date.now();
const ago = (minutes: number) => new Date(now - minutes * 60_000).toISOString();
const ahead = (minutes: number) => new Date(now + minutes * 60_000).toISOString();

export const mockContacts: ContactListItem[] = [
  {
    id: "c-ana-torres",
    agent: "sales",
    phone: "+51 9•• ••• 148",
    username: "anatorres",
    name: "Ana Torres",
    email: "ana.torres@correo.pe",
    stage: "qualified",
    intentScore: 5,
    profile: {
      district: "Santiago de Surco",
      bedrooms: 3,
      budgetMax: 460000,
      downPayment: 65000,
      projectInterest: "Parques de Surco",
      objections: "Quiere comparar la cuota con otro proyecto",
      notes: "Prefiere visitas los sábados antes del mediodía",
    },
    lastInboundAt: ago(18),
    lastOutboundAt: ago(17),
    nextFollowUpAt: ahead(90),
    sessionOpen: true,
    assignedTo: "Alejandro",
    createdAt: ago(4320),
    updatedAt: ago(17),
    lastMessagePreview: "Sí, el sábado a las 11 me funciona. ¿Puedo ir con mi esposo?",
  },
  {
    id: "c-luis-mendoza",
    agent: "housing",
    phone: "+51 9•• ••• 602",
    username: null,
    name: "Luis Mendoza",
    email: null,
    stage: "qualifying",
    intentScore: 4,
    profile: {
      district: "Comas",
      monthlyIncome: 4200,
      monthlyDebts: 350,
      downPayment: 18000,
      programInterest: "Nuevo Crédito Mivivienda",
      notes: "Trabaja en planilla; compra con su pareja",
    },
    lastInboundAt: ago(52),
    lastOutboundAt: ago(50),
    nextFollowUpAt: null,
    sessionOpen: true,
    assignedTo: "Mariana",
    createdAt: ago(2880),
    updatedAt: ago(50),
    lastMessagePreview: "Entre los dos ganamos un poco más de S/ 4,000. ¿Alcanza?",
  },
  {
    id: "c-camila-rojas",
    agent: "sales",
    phone: "+51 9•• ••• 971",
    username: "camirojas",
    name: "Camila Rojas",
    email: "camila.r@correo.pe",
    stage: "visit_scheduled",
    intentScore: 5,
    profile: {
      district: "San Miguel",
      bedrooms: 2,
      budgetMax: 360000,
      projectInterest: "Mar Pacífico",
      notes: "Visita confirmada para mañana a las 16:30",
    },
    lastInboundAt: ago(210),
    lastOutboundAt: ago(205),
    nextFollowUpAt: ahead(1380),
    sessionOpen: true,
    assignedTo: "Juan Pedro",
    createdAt: ago(10080),
    updatedAt: ago(205),
    lastMessagePreview: "Perfecto, ahí estaré mañana. Gracias por la ubicación.",
  },
  {
    id: "c-jorge-quispe",
    agent: "housing",
    phone: "+51 9•• ••• 314",
    username: null,
    name: "Jorge Quispe",
    email: null,
    stage: "nurture",
    intentScore: 3,
    profile: {
      district: "Carabayllo",
      monthlyIncome: 2900,
      monthlyDebts: 0,
      programInterest: "Techo Propio",
      objections: "Aún no completa la inicial",
      notes: "Retomar al cierre de mes",
    },
    lastInboundAt: ago(1770),
    lastOutboundAt: ago(1765),
    nextFollowUpAt: ago(45),
    sessionOpen: false,
    assignedTo: null,
    createdAt: ago(20160),
    updatedAt: ago(1765),
    lastMessagePreview: "Este mes termino de pagar una deuda y lo podemos revisar.",
  },
  {
    id: "c-valeria-paz",
    agent: "sales",
    phone: "+51 9•• ••• 735",
    username: "valepaz",
    name: "Valeria Paz",
    email: null,
    stage: "new",
    intentScore: null,
    profile: { district: "Ate", bedrooms: 2 },
    lastInboundAt: ago(6),
    lastOutboundAt: null,
    nextFollowUpAt: null,
    sessionOpen: true,
    assignedTo: null,
    createdAt: ago(6),
    updatedAt: ago(6),
    lastMessagePreview: "Hola, vi el proyecto de Ate. ¿Todavía tienen depas de 2 dormitorios?",
  },
  {
    id: "c-diego-salazar",
    agent: "housing",
    phone: "+51 9•• ••• 489",
    username: null,
    name: "Diego Salazar",
    email: "dsalazar@correo.pe",
    stage: "qualified",
    intentScore: 4,
    profile: {
      district: "Víctor Larco",
      monthlyIncome: 5100,
      monthlyDebts: 600,
      downPayment: 25000,
      programInterest: "Nuevo Crédito Mivivienda",
      projectInterest: "Ribera del Moche",
    },
    lastInboundAt: ago(610),
    lastOutboundAt: ago(605),
    nextFollowUpAt: ago(10),
    sessionOpen: true,
    assignedTo: "Mariana",
    createdAt: ago(8640),
    updatedAt: ago(605),
    lastMessagePreview: "Mándame por favor los requisitos para avanzar con la evaluación.",
  },
  {
    id: "c-renato-arias",
    agent: "sales",
    phone: "+51 9•• ••• 820",
    username: null,
    name: "Renato Arias",
    email: null,
    stage: "lost",
    intentScore: 2,
    profile: {
      district: "San Miguel",
      budgetMax: 220000,
      objections: "Presupuesto por debajo del inventario",
    },
    lastInboundAt: ago(7560),
    lastOutboundAt: ago(7550),
    nextFollowUpAt: null,
    sessionOpen: false,
    assignedTo: "Alejandro",
    createdAt: ago(12960),
    updatedAt: ago(7550),
    lastMessagePreview: "Gracias, por ahora está fuera de mi presupuesto.",
  },
  {
    id: "c-sofia-vargas",
    agent: "housing",
    phone: "+51 9•• ••• 057",
    username: "sofiavargas",
    name: "Sofía Vargas",
    email: "sofia.vargas@correo.pe",
    stage: "won",
    intentScore: 5,
    profile: {
      district: "Comas",
      monthlyIncome: 4800,
      monthlyDebts: 100,
      downPayment: 32000,
      programInterest: "Techo Propio",
      projectInterest: "Alameda Norte",
      notes: "Separación registrada; documentación completa",
    },
    lastInboundAt: ago(2900),
    lastOutboundAt: ago(2890),
    nextFollowUpAt: null,
    sessionOpen: false,
    assignedTo: "Juan Pedro",
    createdAt: ago(43200),
    updatedAt: ago(2890),
    lastMessagePreview: "¡Listo! Ya envié el voucher de separación.",
  },
];

export const mockMessages: Message[] = [
  { id: "m1", contactId: "c-ana-torres", role: "human", content: "Hola, busco un departamento en Surco para mi familia.", kapsoId: "mock-1", createdAt: ago(62) },
  { id: "m2", contactId: "c-ana-torres", role: "ai", content: "¡Hola, Ana! Soy Tami. Tenemos opciones de 2 y 3 dormitorios en Surco. ¿Qué presupuesto aproximado y número de dormitorios tienes en mente?", kapsoId: "mock-2", createdAt: ago(60) },
  { id: "m3", contactId: "c-ana-torres", role: "human", content: "Hasta S/ 460 mil, tres dormitorios. Tengo S/ 65 mil para la inicial.", kapsoId: "mock-3", createdAt: ago(44) },
  { id: "m4", contactId: "c-ana-torres", role: "ai", content: "Buenísimo. Parques de Surco encaja con ese rango. ¿Te gustaría conocer el piloto esta semana?", kapsoId: "mock-4", createdAt: ago(42) },
  { id: "m5", contactId: "c-ana-torres", role: "advisor", content: "Hola, Ana. Soy Alejandro del equipo comercial. Tengo un espacio el sábado a las 11:00.", kapsoId: "mock-5", createdAt: ago(20) },
  { id: "m6", contactId: "c-ana-torres", role: "human", content: "Sí, el sábado a las 11 me funciona. ¿Puedo ir con mi esposo?", kapsoId: "mock-6", createdAt: ago(18) },
  { id: "m7", contactId: "c-luis-mendoza", role: "human", content: "Quiero saber si puedo comprar con Mivivienda.", kapsoId: "mock-7", createdAt: ago(70) },
  { id: "m8", contactId: "c-luis-mendoza", role: "ai", content: "Te ayudo con una preorientación. ¿Cuál es el ingreso mensual del hogar y tienen alguna deuda activa?", kapsoId: "mock-8", createdAt: ago(68) },
  { id: "m9", contactId: "c-luis-mendoza", role: "human", content: "Entre los dos ganamos un poco más de S/ 4,000. ¿Alcanza?", kapsoId: "mock-9", createdAt: ago(52) },
  { id: "m10", contactId: "c-camila-rojas", role: "advisor", content: "Te comparto la ubicación de la sala de ventas. Te esperamos mañana a las 16:30.", kapsoId: "mock-10", createdAt: ago(205) },
  { id: "m11", contactId: "c-camila-rojas", role: "human", content: "Perfecto, ahí estaré mañana. Gracias por la ubicación.", kapsoId: "mock-11", createdAt: ago(210) },
  { id: "m12", contactId: "c-jorge-quispe", role: "human", content: "Este mes termino de pagar una deuda y lo podemos revisar.", kapsoId: "mock-12", createdAt: ago(1770) },
  { id: "m13", contactId: "c-valeria-paz", role: "human", content: "Hola, vi el proyecto de Ate. ¿Todavía tienen depas de 2 dormitorios?", kapsoId: "mock-13", createdAt: ago(6) },
  { id: "m14", contactId: "c-diego-salazar", role: "human", content: "Mándame por favor los requisitos para avanzar con la evaluación.", kapsoId: "mock-14", createdAt: ago(610) },
  { id: "m15", contactId: "c-renato-arias", role: "human", content: "Gracias, por ahora está fuera de mi presupuesto.", kapsoId: "mock-15", createdAt: ago(7560) },
  { id: "m16", contactId: "c-sofia-vargas", role: "human", content: "¡Listo! Ya envié el voucher de separación.", kapsoId: "mock-16", createdAt: ago(2900) },
];

export const mockFollowUps: FollowUp[] = [
  { id: "f1", contactId: "c-ana-torres", dueAt: ahead(90), status: "pending", note: "Confirmar acompañantes y enviar ubicación", createdAt: ago(20) },
  { id: "f2", contactId: "c-jorge-quispe", dueAt: ago(45), status: "pending", note: "Retomar con plantilla aprobada", createdAt: ago(1440) },
  { id: "f3", contactId: "c-camila-rojas", dueAt: ahead(1380), status: "pending", note: "Recordatorio de visita", createdAt: ago(200) },
  { id: "f4", contactId: "c-diego-salazar", dueAt: ago(10), status: "pending", note: "Enviar checklist de documentos", createdAt: ago(600) },
];
